default['asterisk']['extensions']['static']              = 'yes'
default['asterisk']['extensions']['writeprotect']        = 'no'
default['asterisk']['extensions']['autofallthrough']     = 'yes'
default['asterisk']['extensions']['clearglobalvars']     = 'no'
default['asterisk']['extensions']['priorityjumping']     = 'no'
